### ISSUE TITLE
(bug) Window versus Full-screen truncation

### ISSUE THREAD

**Issue by smonterola** [Project-Babel-World/Babel_World#15]
<img width="1440" alt="Screenshot 2024-04-27 at 7 49 22 PM" src="https://github.com/Project-Babel-World/Babel_World/assets/130492711/73415551-6338-45d9-be97-1374a4fbfaee">
When the game is initially launched, the game is defaulted to windowed mode. The limited field of view was challenging, but I assumed it was part of the game. 
However, upon going into full-screen mode, I realized that the limitation was not maintained.
<img width="1439" alt="Screenshot 2024-04-27 at 7 49 27 PM" src="https://github.com/Project-Babel-World/Babel_World/assets/130492711/23f4204e-ef44-4017-9825-2de3550e917d">

I think that this is a bug because instead of zooming out to fit the game in a smaller window, the game instead truncates the screen.
The game looks good otherwise though! It looks like it will be a fun project.

**Comment by snelso24** [comment]
Thanks Sam! Bug fixed :)
